# andrew-insurer ENV
apiVersion: v1
kind: ConfigMap
metadata:
  name: andrew-insurer-configmap
data:
  NODE_ENV: "production"
---
# andrew-insurer ENV SECRETS (BASE64)
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: andrew-insurer-secrets
data: {}
---
# andrew-insurer DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: andrew-insurer-deployment
  labels:
    tier: andrew-insurer
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      tier: andrew-insurer
  template:
    metadata:
      labels:
        tier: andrew-insurer
    spec:
      containers:
        - name: andrew-insurer
          image: antoineleguillou/andrew-insurer:14-03-2024.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 350m
              memory: 450Mi
            requests:
              cpu: 250m
              memory: 250Mi
          envFrom:
            - configMapRef:
                name: andrew-insurer-configmap
            - secretRef:
                name: andrew-insurer-secrets
          ports:
            - containerPort: 3000
            - containerPort: 3001
      restartPolicy: Always
---
# andrew-insurer SERVICES
apiVersion: v1
kind: Service
metadata:
  name: andrew-insurer-service
spec:
  selector:
    tier: andrew-insurer
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: public