export enum ApplicationStatus {
  PENDING = "PENDING",
  REVIEWING = "REVIEWING",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED",
  PAYMENT_CANCELED = "PAYMENT_CANCELED",
  TO_AMMEND = "TO_AMMEND",
  REJECTED = "REJECTED",
}
